/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_isp_num: 1
      i_isp_den: 5
      i_max_q_size: 1
      i_fps: 10.0
      i_width: 384
      i_height: 216
    rgb:
      i_isp_num: 1
      i_isp_den: 5
      i_max_q_size: 1
      rgb_i_set_isp_scale: true
      i_fps: 10.0
      i_width: 384
      i_height: 216
    stereo:
      # i_subpixel: true
      i_subpixel: false
      i_isp_num: 1
      i_isp_den: 5
      i_max_q_size: 1
      i_fps: 10.0
      i_width: 384
      i_height: 216
      i_publish_left_rect: false
      i_publish_right_rect: false
    left:
      i_isp_num: 1
      i_isp_den: 5
      i_max_q_size: 1
      i_width: 384
      i_height: 216
      i_fps: 10.0      
      i_publish_topic: true   
    right:
      i_isp_num: 1
      i_isp_den: 5
      i_max_q_size: 1
      i_width: 384
      i_height: 216
      i_fps: 10.0      
      i_publish_topic: true
